### ISSUE TITLE
Missing main switch

### ISSUE THREAD

**Issue by Arnaud73** [militu/electrical-panel-label#2]
My enclosure contains some "interrupteur" which are not "disjoncteur" nor "différentiel".

Also, in the same category, "para-foudre" would be welcome.

**Comment by militu** [comment]
Ok for "parafoudre"! 
Regarding the "interrupteur," @Arnaud73  could you please provide more details about its specific function or type? This information will help me better understand which name and logo would be most appropriate to use.

**Comment by Arnaud73** [comment]
Here is one example: https://elec44.fr/interrupteurs-modulaires-bipolaires/107166-hager-interrupteur-modulaire-2-poles-63a-ref-sbn263-3250615510211.html

It physically looks like an "interrupteur différentiel" or a "disjoncteur", but it's neither of them: it does not switch off when current is leaking or when current exceeds a specific limit. It is just a "dumb" switch that can be used to switch of power, just like basic switches we find everywhere in a house.

For large enclosures, 2, 3, 4+ rows, it acts like a quick disconnect to switch everything off, especially useful when the "disjoncteur d'abonné" is far away (next to the street for example)
