### ISSUE TITLE
Power-plugs

### ISSUE THREAD

**Issue by Arnaud73** [militu/electrical-panel-label#3]
My enclosure contains power plugs which are 2,5 elements wide. They break the layout (in my cas, I got lucky, I have 2 of them next to one another, so it is 5 elements wide)

Here is an example from Hager: https://hager.com/fr/catalogue/produits/sns216-pc-16a-2p-t-sanvis-fr

I think, Schneider and Legrand provide the same kind of power plugs.

**Comment by militu** [comment]
@Arnaud73  Are you saying you would want to have 0.5 increment in the module sizes? Will it solve your issue?

**Comment by Arnaud73** [comment]
@militu, I'm not sure there are that many 0,5 and 1,5 sizes, so adding them would be counterproductive. Maybe 2,5 alone, would be useful (with the additional entry for power sockets).
